# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, height_field=128, storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole('reader'), gdstorage.storage.GoogleDrivePermissionType('user'), 'jhjaquintero@gmail.com'),)), upload_to='/perfil/', width_field=128),
        ),
    ]
